version: '2'
services:

  express-test:
    image: test-docker
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: on-failure 
    ports:
      - 3000:3000
    depends_on:
      - calvin-cassandra
    
  calvin-cassandra:
    image: cassandra:latest 
    network_mode: host
    restart: on-failure
    expose: 
      - 9042      